export const productsData = {
    "productDetails": [
        {
            "imageURl": "https://rukminim1.flixcart.com/image/660/792/kflftzk0/jacket/p/z/z/xxl-1285-fk-breil-by-fort-collins-original-imafwyyegzzyx6s5.jpeg?q=50",
            "productTitle": "Breil By Fort Collins",
            "productDescription": "Full sleeve Men",
            "newPrice": 985,
            "oldPrice": 2325,
            "discountAmount": 1340,
            "discount":"57% off",
            "size":"M",
            "id":"1",
            "idealFor":"men",
            "cartTotal":0,
            "savedForLater":"false",
        },
        {
            "imageURl": "https://rukminim1.flixcart.com/image/660/792/kr9jafk0/jacket/j/r/f/m-545-fk-fort-collins-original-imag5389rzccsghz.jpeg?q=50",
            "productTitle": "Fort Collins",
            "productDescription": "Full sleeve Men Jacket",
            "newPrice": 697,
            "oldPrice": 2325,
            "discountAmount": 1628,
            "discount":"70% off",
            "size":"M",
            "id":"2",
            "idealFor":"men",
            "cartTotal":0,
            "savedForLater":"false",
        },
        {
            "imageURl": "https://rukminim1.flixcart.com/image/660/792/kgsb1jk0/cap/h/y/g/free-stylish-black-balkalova-cap-fashlook-original-imafwy64umkfsefu.jpeg?q=50",
            "productTitle": "Freeze",
            "productDescription": "Woolen cap",
            "newPrice": 218,
            "oldPrice": 1057,
            "discountAmount": 839,
            "discount":"79% off",
            "size":"S",
             "id":"3",
             "idealFor":"children",
             "cartTotal":0,
             "savedForLater":"false",
        },
        {
            "imageURl": "https://rukminim1.flixcart.com/image/660/792/ki6bgcw0-0/cap/4/t/d/free-black-men-cap-with-neck-scarf-amormente-original-imafyf2ugjtcaf7g.jpeg?q=50",
            "productTitle": "AmorMente",
            "productDescription": "Solid cap with neck",
            "newPrice": 207,
            "oldPrice": 899,
            "discountAmount": 692,
            "discount":"76% off",
            "size":"S",
             "id":"4",
             "idealFor":"women",
             "cartTotal":0,
             "savedForLater":"false",
        },
         {
            "imageURl": "https://rukminim1.flixcart.com/image/660/792/kfoapow0-0/sock/i/t/e/free-fj-al-mix-3-slimshine-original-imafw2uyddzevvyw.jpeg?q=50",
            "productTitle": "SLIMSHINE",
            "productDescription": "Men Ankle length",
            "newPrice": 134,
            "oldPrice": 699,
            "discountAmount": 565,
            "discount":"80% off",
            "size":"L",
             "id":"5",
             "idealFor":"men",
             "cartTotal":0,
             "savedForLater":"false",
        },
        {
            "imageURl": "https://rukminim1.flixcart.com/image/660/792/kl2mljk0/t-shirt/a/3/k/4xl-tblhdfulmask-lion-tripr-original-imagy9tcx7q25wym.jpeg?q=50",
            "productTitle": "TRIPR",
            "productDescription": "Printed Men T-shirt",
            "newPrice": 282,
            "oldPrice": 1399,
            "discountAmount": 1117,
            "discount":"79% off",
            "size":"XL",
             "id":"6",
             "idealFor":"men",
             "cartTotal":0,
             "savedForLater":"false",
        },
        // {
        //     "imageURl": "https://rukminim1.flixcart.com/image/660/792/kv6zvrk0/cap/l/f/d/free-wc-nck-broen-original-imag84z3t4h7zfkz.jpeg?q=50",
        //     "productTitle": "Muffler",
        //     "productDescription": "Broen solid men",
        //     "newPrice": "247",
        //     "oldPrice": "799",
        //     "discount":"69% off",
        //     "size":"L",
        //      "id":"7",
        // },
        // {
        //     "imageURl": "https://rukminim1.flixcart.com/image/660/792/kj36ky80-0/cap/6/e/7/free-cap-123-kittuu-original-imafyprwcebnnucq.jpeg?q=50",
        //     "productTitle": "Kittuu",
        //     "productDescription": "Winter cap with neck",
        //     "newPrice": "234",
        //     "oldPrice": "999",
        //     "discount":"76% off",
        //     "size":"M",
        //      "id":"8",
        // },
    ]
}